import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import { Clapperboard, Play, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

async function fetchGenres(): Promise<{ id: string; name: string }[]> {
	const res = await fetch("https://api.themoviedb.org/3/genre/movie/list", {
		headers: {
			Authorization: `Bearer ${process.env.TMDB_TOKEN}`,
		},
	});

	const data = await res.json();
    return data.genres;
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const genres = await fetchGenres();

    async function searchMovie(formData: FormData) {
		"use server";

		const q= formData.get('q');
        redirect(`/search?q=${q}`);
	}

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<header className="p-4 border-b flex justify-between">
					<h1 className="font-bold text-2xl flex gap-2 items-center">
						<Clapperboard />
						Next Movie
					</h1>
					<form className="flex gap-1" action={searchMovie}>
						<Input placeholder="Search" name="q" />
						<Button type="submit">
							<Search />
						</Button>
					</form>
				</header>
				<main className="flex">
					<nav className="w-70 p-4 border-r flex flex-col gap-2">
						<Button
							variant="outline"
							asChild>
							<Link
								href="/"
								className="flex justify-start">
								<Play />
								All Genre
							</Link>
						</Button>
						{genres.map(genre => {
							return (
								<Button
									key={genre.id}
									variant="outline"
									className="w-full"
									asChild>
									<Link
										href={`/genre/${genre.name}/${genre.id}`}
										className="flex justify-start">
										<Play />
										{genre.name}
									</Link>
								</Button>
							);
						})}
					</nav>
					<section className="p-4">{children}</section>
				</main>
			</body>
		</html>
	);
}
